FROM ckan/ckan-base:2.11

# Install any extensions needed by your CKAN instance
# See Dockerfile.dev for more details and examples

# Copy custom initialization scripts
COPY --chown=ckan-sys:ckan-sys docker-entrypoint.d/* /docker-entrypoint.d/

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY --chown=ckan-sys:ckan-sys patches ${APP_DIR}/patches

# Copy override files in setup/
COPY setup/prerun.py.override ${APP_DIR}/prerun.py

USER root

# Install debugging/network tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        iputils-ping \
        netcat-openbsd \
        dnsutils \
        procps \
        curl \
        wget \
        vim-tiny \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /stupid/test/incineroar \
&& chown -R root:0 /stupid/test/incineroar \
&& chmod -R g+rwX /stupid/test/incineroar

RUN chgrp -R 0 ${APP_DIR} && \
    chmod -R g=u ${APP_DIR}

USER ckan

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done