apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/incineroar/ckan-postgres:1.2
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: ckan-postgres-secret
          volumeMounts:
            - name: ckan-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: ckan-postgres-data
          persistentVolumeClaim:
            claimName: ckan-postgres-data
