apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6
          args:
            - redis-server
            - --save ""
            - --appendonly no
            - --bind 0.0.0.0
            - --protected-mode no
          ports:
            - containerPort: 6379