apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckan-redis
  template:
    metadata:
      labels:
        app: ckan-redis
    spec:
      containers:
        - name: redis
          image: redis:6
          args:
            - redis-server
            - --save ""
            - --appendonly no
            - --bind 0.0.0.0
            - --protected-mode no
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: ckan-redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: ckan-redis