apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckan-solr
  template:
    metadata:
      labels:
        app: ckan-solr
    spec:
      containers:
        - name: solr
          image: quay.io/incineroar/ckan-solr:1.0
          ports:
            - containerPort: 8983
          volumeMounts:
            - name: ckan-solr-data
              mountPath: /var/solr
      volumes:
        - name: ckan-solr-data
          persistentVolumeClaim:
            claimName: ckan-solr-data

---

apiVersion: v1
kind: Service
metadata:
  name: ckan-solr
  labels:
    app: ckan-solr
spec:
  ports:
    - name: solr
      port: 8983          # The port the service exposes internally
      targetPort: 8983    # Must match the Solr container port
  selector:
    app: ckan-solr
