apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan-xloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckan-xloader
  template:
    metadata:
      labels:
        app: ckan-xloader
        app.kubernetes.io/part-of: ckan
    spec:
      containers:
      - name: ckan-xloader
        image: quay.io/incineroar/ckan-xloader:1.9
        envFrom:
        - configMapRef:
            name: ckan-config
        - secretRef:
            name: ckan-secret
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
