apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: ckan
  name: ckan
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: ckan/ckan-base:2.11
      name: "2.11"
      referencePolicy:
        type: ""
