apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: ckan/ckan-base-datapusher:0.0.21
      name: 0.0.21
      referencePolicy:
        type: ""
