apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432          # The port the service exposes internally
      targetPort: 5432    # Must match the Postgres container port
  selector:
    app: postgres
