apiVersion: v1
kind: Service
metadata:
  name: ckan-solr
  labels:
    app: solr
spec:
  ports:
    - name: solr
      port: 8983          # The port the service exposes internally
      targetPort: 8983    # Must match the Solr container port
  selector:
    app: solr
