apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckan-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName can be omitted to use the default StorageClass
  # of the OpenShift sandbox
