apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckan-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName can be omitted to use the default StorageClass
  # of the OpenShift sandbox
