apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    io.kompose.service: nginx
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: ' '
          name: nginx
          ports:
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - nginx
        from:
          kind: ImageStreamTag
          name: nginx:1.25
      type: ImageChange
