apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ckan
  name: ckan
spec:
  ports:
    - name: http
      port: 5000        # This is the port Nginx will use
      targetPort: 5000  # Must match the container port in the CKAN pod
  selector:
    io.kompose.service: ckan
