apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  # Name of postgres cluster
  name: ckan-db
  namespace: aafc-labs-can-dev
spec:
  # The official ckan-docker implementation uses postgres:16-alpine
  postgresVersion: 16
  instances:
    - name: instance1
      replicas: 2
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      dataVolumeClaimSpec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
  users:
    - name: ckandbuser
      databases:
        - ckandb
        - datastore
        - ckan_test
        - datastore_test
      options: "CREATEDB CREATEROLE"
    - name: datastore
  databaseInitSQL:
    key: init.sql
    name: ckan-init-sql

  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: "100"
